INSERT INTO t_category_data (n_id, c_label, c_value, n_seq, c_created_by, c_updated_by, d_created_at, d_updated_at, c_domain) VALUES (33, 'Non Technical', 'Finance', 0, 'RADIFAN FARIZ', '', '2024-07-19 11:25:14', null, 'Specialist');
INSERT INTO t_category_data (n_id, c_label, c_value, n_seq, c_created_by, c_updated_by, d_created_at, d_updated_at, c_domain) VALUES (34, 'technical', 'Marketing', 0, 'RADIFAN FARIZ', '', '2024-07-19 11:34:51', null, 'specialist');
INSERT INTO t_category_data (n_id, c_label, c_value, n_seq, c_created_by, c_updated_by, d_created_at, d_updated_at, c_domain) VALUES (35, 'non technical', 'Legal', 0, 'RADIFAN FARIZ', '', '2024-07-19 11:35:25', null, 'general');
INSERT INTO t_category_data (n_id, c_label, c_value, n_seq, c_created_by, c_updated_by, d_created_at, d_updated_at, c_domain) VALUES (36, 'non technical', 'GA', 0, 'RADIFAN FARIZ', '', '2024-07-19 11:35:38', null, 'general');
INSERT INTO t_category_data (n_id, c_label, c_value, n_seq, c_created_by, c_updated_by, d_created_at, d_updated_at, c_domain) VALUES (38, 'non technical', 'Accounting', 0, 'RADIFAN FARIZ', '', '2024-07-25 17:35:02', null, 'specialist');
INSERT INTO t_category_data (n_id, c_label, c_value, n_seq, c_created_by, c_updated_by, d_created_at, d_updated_at, c_domain) VALUES (39, 'technical', 'Accounting', 0, 'RADIFAN FARIZ', '', '2024-07-25 17:35:31', null, 'general');
INSERT INTO t_category_data (n_id, c_label, c_value, n_seq, c_created_by, c_updated_by, d_created_at, d_updated_at, c_domain) VALUES (40, 'technical', 'People Development', 0, 'RADIFAN FARIZ', '', '2024-07-25 17:36:09', null, 'general');
INSERT INTO t_category_data (n_id, c_label, c_value, n_seq, c_created_by, c_updated_by, d_created_at, d_updated_at, c_domain) VALUES (41, 'technical', 'SP - IT', 0, 'MUHAMMAD TANAKA', '', '2024-07-26 17:39:58', null, 'specialist');
INSERT INTO t_category_data (n_id, c_label, c_value, n_seq, c_created_by, c_updated_by, d_created_at, d_updated_at, c_domain) VALUES (42, 'non technical', 'GN - IT', 0, 'MUHAMMAD TANAKA', '', '2024-07-26 17:41:55', null, 'general');
