DROP SEQUENCE lms_module_data_n_id_seq;
CREATE SEQUENCE lms_module_data_n_id_seq INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1  NO CYCLE;
DROP SEQUENCE lms_modules_n_id_seq;
CREATE SEQUENCE lms_modules_n_id_seq INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1  NO CYCLE;
DROP SEQUENCE lms_posttest_data_n_id_seq;
CREATE SEQUENCE lms_posttest_data_n_id_seq INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1  NO CYCLE;
DROP SEQUENCE lms_posttest_metadata_n_id_seq;
CREATE SEQUENCE lms_posttest_metadata_n_id_seq INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1  NO CYCLE;
DROP SEQUENCE lms_pretest_metadata_n_id_seq;
CREATE SEQUENCE lms_pretest_metadata_n_id_seq INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1  NO CYCLE;
DROP SEQUENCE t_access_data_n_id_seq;
CREATE SEQUENCE t_access_data_n_id_seq INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1  NO CYCLE;
DROP SEQUENCE t_materi_data_n_id_seq;
CREATE SEQUENCE t_materi_data_n_id_seq INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1  NO CYCLE;
DROP SEQUENCE t_materi_metadata_n_id_seq;
CREATE SEQUENCE t_materi_metadata_n_id_seq INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1  NO CYCLE;
DROP SEQUENCE t_materi_result_n_id_seq;
CREATE SEQUENCE t_materi_result_n_id_seq INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1  NO CYCLE;
DROP SEQUENCE t_posttest_result_data_n_id_seq;
CREATE SEQUENCE t_posttest_result_data_n_id_seq INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1  NO CYCLE;
DROP SEQUENCE t_pretest_data_n_id_seq;
CREATE SEQUENCE t_pretest_data_n_id_seq INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1  NO CYCLE;
DROP SEQUENCE t_pretest_result_data_n_id_seq;
CREATE SEQUENCE t_pretest_result_data_n_id_seq INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1  NO CYCLE;
DROP SEQUENCE t_user_action_n_id_seq;
CREATE SEQUENCE t_user_action_n_id_seq INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1  NO CYCLE;
DROP SEQUENCE t_user_data_n_id_seq;
CREATE SEQUENCE t_user_data_n_id_seq INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1  NO CYCLE;
DROP TABLE t_access_data;
CREATE TABLE t_access_data (n_id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY, n_module_id INTEGER, c_created_by CHARACTER VARYING, c_updated_by CHARACTER VARYING, d_created_at TIMESTAMP(6) WITHOUT TIME ZONE, d_updated_at TIMESTAMP(6) WITHOUT TIME ZONE, c_global_id CHARACTER VARYING, n_array_grade_id INTEGER[], n_array_user_id INTEGER[], PRIMARY KEY (n_id));
DROP TABLE t_materi_data;
CREATE TABLE t_materi_data (n_id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY, n_module_id INTEGER, n_materi_meta_id INTEGER, c_global_id CHARACTER VARYING, c_type CHARACTER VARYING, c_src CHARACTER VARYING, b_ispublished BOOLEAN, c_name CHARACTER VARYING, c_description CHARACTER VARYING, c_created_by CHARACTER VARYING, c_updated_by CHARACTER VARYING, d_created_at TIMESTAMP(6) WITHOUT TIME ZONE DEFAULT now(), d_updated_at TIMESTAMP(6) WITHOUT TIME ZONE DEFAULT now(), PRIMARY KEY (n_id));
DROP TABLE t_materi_metadata;
CREATE TABLE t_materi_metadata (n_id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY, n_module_id INTEGER, c_global_id CHARACTER VARYING, c_name CHARACTER VARYING, c_description CHARACTER VARYING, c_src CHARACTER VARYING, c_created_by CHARACTER VARYING, c_updated_by CHARACTER VARYING, d_created_at TIMESTAMP(6) WITHOUT TIME ZONE DEFAULT now(), d_updated_at TIMESTAMP(6) WITHOUT TIME ZONE DEFAULT now(), PRIMARY KEY (n_id));
DROP TABLE t_materi_result_data;
CREATE TABLE t_materi_result_data (n_id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY, n_user_id INTEGER, c_global_id CHARACTER VARYING, d_start TIMESTAMP(6) WITHOUT TIME ZONE, d_end TIMESTAMP(6) WITHOUT TIME ZONE, d_duration INTERVAL(6), c_created_by CHARACTER VARYING, c_updated_by CHARACTER VARYING, d_created_at TIMESTAMP(6) WITHOUT TIME ZONE DEFAULT now(), d_updated_at TIMESTAMP(6) WITHOUT TIME ZONE DEFAULT now(), n_materi_id INTEGER, CONSTRAINT t_materi_result_pkey PRIMARY KEY (n_id));
DROP TABLE t_module_data;
CREATE TABLE t_module_data (n_id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY, c_global_id CHARACTER VARYING, n_module_meta_id INTEGER, n_pretest_meta_id INTEGER, n_pretest_id INTEGER, n_materi_meta_id INTEGER, n_materi_id INTEGER, n_posttest_meta_id INTEGER, n_posttest_id INTEGER, n_user_id INTEGER, n_grade_id INTEGER, b_ispublished BOOLEAN, c_created_by CHARACTER VARYING, d_created_at TIMESTAMP(6) WITHOUT TIME ZONE, c_updated_by CHARACTER VARYING, d_updated_at TIMESTAMP(6) WITHOUT TIME ZONE, CONSTRAINT lms_module_data_pkey PRIMARY KEY (n_id));
DROP TABLE t_module_metadata;
CREATE TABLE t_module_metadata (n_id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY, c_global_id CHARACTER VARYING, c_name CHARACTER VARYING, c_description CHARACTER VARYING, c_src CHARACTER VARYING, c_learning_journey CHARACTER VARYING, c_category CHARACTER VARYING, n_max_month INTEGER, c_created_by CHARACTER VARYING, c_updated_by CHARACTER VARYING, d_created_at TIMESTAMP(6) WITHOUT TIME ZONE, d_updated_at TIMESTAMP(6) WITHOUT TIME ZONE, CONSTRAINT modules_pkey PRIMARY KEY (n_id));
DROP TABLE t_posttest_data;
CREATE TABLE t_posttest_data (n_id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY, n_module_id INTEGER, n_posttest_meta_id INTEGER, c_global_id CHARACTER VARYING, j_question JSONB, c_created_by CHARACTER VARYING, c_updated_by CHARACTER VARYING, d_created_at TIMESTAMP(6) WITHOUT TIME ZONE DEFAULT now(), d_updated_at TIMESTAMP(6) WITHOUT TIME ZONE DEFAULT now(), b_ispublished BOOLEAN, CONSTRAINT lms_posttest_data_pkey PRIMARY KEY (n_id));
DROP TABLE t_posttest_metadata;
CREATE TABLE t_posttest_metadata (n_id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY, n_module_id INTEGER, c_global_id CHARACTER VARYING, c_name CHARACTER VARYING, c_description CHARACTER VARYING, n_max_access INTEGER, n_min_score DOUBLE PRECISION, c_created_by CHARACTER VARYING, c_updated_by CHARACTER VARYING, d_created_at TIMESTAMP(6) WITHOUT TIME ZONE, d_updated_at TIMESTAMP(6) WITHOUT TIME ZONE, c_src CHARACTER VARYING, CONSTRAINT lms_posttest_metadata_pkey PRIMARY KEY (n_id));
DROP TABLE t_posttest_result_data;
CREATE TABLE t_posttest_result_data (n_id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY, n_user_id INTEGER, n_score DOUBLE PRECISION, d_start TIMESTAMP(6) WITHOUT TIME ZONE, d_end TIMESTAMP(6) WITHOUT TIME ZONE, d_duration INTERVAL(6), j_answer JSONB, j_question_answered JSONB, c_created_by CHARACTER VARYING, c_updated_by CHARACTER VARYING, d_created_at TIMESTAMP(6) WITHOUT TIME ZONE, d_updated_at TIMESTAMP(6) WITHOUT TIME ZONE, c_global_id CHARACTER VARYING, PRIMARY KEY (n_id));
DROP TABLE t_pretest_data;
CREATE TABLE t_pretest_data (n_id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY, n_module_id INTEGER, n_pretest_meta_id INTEGER, c_global_id CHARACTER VARYING, j_question JSONB, b_ispublished BOOLEAN, c_created_by CHARACTER VARYING, c_updated_by CHARACTER VARYING, d_created_at TIMESTAMP(6) WITHOUT TIME ZONE DEFAULT now(), d_updated_at TIMESTAMP(6) WITHOUT TIME ZONE DEFAULT now(), CONSTRAINT lms_pretest_data_pkey PRIMARY KEY (n_id));
DROP TABLE t_pretest_metadata;
CREATE TABLE t_pretest_metadata (n_id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY, n_module_id INTEGER, c_global_id CHARACTER VARYING, c_name CHARACTER VARYING, c_description CHARACTER VARYING, n_max_access INTEGER, n_min_score DOUBLE PRECISION, c_created_by CHARACTER VARYING, c_updated_by CHARACTER VARYING, d_created_at TIMESTAMP(6) WITHOUT TIME ZONE DEFAULT now(), d_updated_at TIMESTAMP(6) WITHOUT TIME ZONE DEFAULT now(), c_src CHARACTER VARYING, CONSTRAINT lms_pretest_metadata_pkey PRIMARY KEY (n_id));
DROP TABLE t_pretest_result_data;
CREATE TABLE t_pretest_result_data (n_id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY, n_user_id INTEGER, n_score DOUBLE PRECISION, d_start TIMESTAMP(6) WITHOUT TIME ZONE, d_end TIMESTAMP(6) WITHOUT TIME ZONE, d_duration INTERVAL(6), j_answer JSONB, j_question_answered JSONB, c_created_by CHARACTER VARYING, c_updated_by CHARACTER VARYING, d_created_at TIMESTAMP(6) WITHOUT TIME ZONE DEFAULT now(), d_updated_at TIMESTAMP(6) WITHOUT TIME ZONE DEFAULT now(), c_global_id CHARACTER VARYING, PRIMARY KEY (n_id));
DROP TABLE t_user_action_data;
CREATE TABLE t_user_action_data (n_id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY, n_user_id INTEGER, c_global_id CHARACTER VARYING, b_isstartcourse BOOLEAN, n_module_accessed INTEGER, n_pretest_accessed INTEGER, n_materi_accessed INTEGER, n_posttest_accessed INTEGER, c_created_by CHARACTER VARYING, c_updated_by CHARACTER VARYING, d_created_at TIMESTAMP(6) WITHOUT TIME ZONE DEFAULT now(), d_updated_at TIMESTAMP(6) WITHOUT TIME ZONE DEFAULT now(), CONSTRAINT t_user_action_pkey PRIMARY KEY (n_id));
DROP TABLE t_user_data;
CREATE TABLE t_user_data (n_id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY, n_employee_id INTEGER, c_name CHARACTER VARYING, c_nik CHARACTER VARYING, c_level CHARACTER VARYING, n_level_id INTEGER, c_grade CHARACTER VARYING, n_grade_id INTEGER, c_department CHARACTER VARYING, n_department_id INTEGER, n_learning_journey_id INTEGER, c_learning_journey CHARACTER VARYING, n_role_id INTEGER, c_role CHARACTER VARYING, n_status_id INTEGER, c_status CHARACTER VARYING, b_isactive BOOLEAN, c_created_by CHARACTER VARYING, c_updated_by CHARACTER VARYING, d_created_at TIMESTAMP(6) WITHOUT TIME ZONE DEFAULT now(), d_updated_at TIMESTAMP(6) WITHOUT TIME ZONE DEFAULT now(), c_alternative_id CHARACTER VARYING, c_password CHARACTER VARYING, n_position_id INTEGER, c_position CHARACTER VARYING, c_main_company CHARACTER VARYING, n_main_company_id INTEGER, PRIMARY KEY (n_id));
ALTER TABLE "t_access_data" ADD CONSTRAINT taccessdata_fk1 FOREIGN KEY ("n_module_id") REFERENCES "t_module_data" ("n_id") ON DELETE CASCADE;
ALTER TABLE "t_materi_data" ADD CONSTRAINT tmateridata_fk1 FOREIGN KEY ("n_materi_meta_id") REFERENCES "t_materi_metadata" ("n_id") ON DELETE CASCADE;
ALTER TABLE "t_materi_result_data" ADD CONSTRAINT tmateriresultdata_fk2 FOREIGN KEY ("n_materi_id") REFERENCES "t_materi_data" ("n_id");
ALTER TABLE "t_materi_result_data" ADD CONSTRAINT tmateriresultdata_fk1 FOREIGN KEY ("n_user_id") REFERENCES "t_user_data" ("n_id");
ALTER TABLE "t_module_data" ADD CONSTRAINT tmoduledata_fk1 FOREIGN KEY ("n_module_meta_id") REFERENCES "t_module_metadata" ("n_id") ON DELETE CASCADE;
ALTER TABLE "t_module_data" ADD CONSTRAINT tmoduledata_fk2 FOREIGN KEY ("n_pretest_meta_id") REFERENCES "t_pretest_metadata" ("n_id") ON DELETE CASCADE;
ALTER TABLE "t_module_data" ADD CONSTRAINT tmoduledata_fk3 FOREIGN KEY ("n_materi_meta_id") REFERENCES "t_materi_metadata" ("n_id") ON DELETE CASCADE;
ALTER TABLE "t_module_data" ADD CONSTRAINT tmoduledata_fk4 FOREIGN KEY ("n_posttest_meta_id") REFERENCES "t_posttest_metadata" ("n_id") ON DELETE CASCADE;
ALTER TABLE "t_posttest_data" ADD CONSTRAINT tposttestdata_fk1 FOREIGN KEY ("n_posttest_meta_id") REFERENCES "t_posttest_metadata" ("n_id") ON DELETE CASCADE;
ALTER TABLE "t_posttest_result_data" ADD CONSTRAINT tposttestresultdata_fk1 FOREIGN KEY ("n_user_id") REFERENCES "t_user_data" ("n_id");
ALTER TABLE "t_pretest_data" ADD CONSTRAINT tpretestdata_fk1 FOREIGN KEY ("n_pretest_meta_id") REFERENCES "t_pretest_metadata" ("n_id") ON DELETE CASCADE;
ALTER TABLE "t_pretest_result_data" ADD CONSTRAINT tpretestresultdata_fk1 FOREIGN KEY ("n_user_id") REFERENCES "t_user_data" ("n_id");
ALTER TABLE "t_user_action_data" ADD CONSTRAINT tuseraction_fk1 FOREIGN KEY ("n_user_id") REFERENCES "t_user_data" ("n_id");
